{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "49c15aff",
   "metadata": {},
   "outputs": [],
   "source": [
    "from oyv.imports import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3a7d183a",
   "metadata": {},
   "outputs": [],
   "source": [
    "ddir = '/home/oyvindl/work/projects/barents_glaciers/glacierocean-austfonna/data/glacier_fronts/python/'\n",
    "fn_in = 'NORDAUSTLANDET_ADVRATES.p'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "92dcf215",
   "metadata": {},
   "outputs": [],
   "source": [
    "d = pickle_load(ddir + fn_in)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "bbc02801",
   "metadata": {},
   "outputs": [],
   "source": [
    "ewkeys = d.glacier_sorting.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e1d59fd2",
   "metadata": {},
   "outputs": [],
   "source": [
    "figdir = './advrate_figures/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "1f0cba5d",
   "metadata": {},
   "outputs": [],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "af83002d",
   "metadata": {},
   "outputs": [],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "535423bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n"
     ]
    }
   ],
   "source": [
    "ti = np.arange(date2num(d.time[0]), date2num(d.time[-1])+1, 0.5)\n",
    "fs = 15 \n",
    "\n",
    "\n",
    "for ewkey in ewkeys:\n",
    "    figdir_ew = figdir + '%s/'%ewkey\n",
    "\n",
    "    glkeys = d.glacier_sorting[ewkey]\n",
    "    \n",
    "    for glkey in glkeys:\n",
    "        \n",
    "        fig, ax = plt.subplots(figsize = (6, 3))\n",
    "        \n",
    "        advrate = d[glkey]\n",
    "\n",
    "        advrate_pos = ip.interp1(date2num(d.time), advrate.copy(), ti)\n",
    "        advrate_neg = ip.interp1(date2num(d.time), advrate.copy(), ti)\n",
    "        advrate_pos[advrate_pos<0] = np.nan\n",
    "        advrate_neg[advrate_neg>0] = np.nan\n",
    "        \n",
    "        fillkws = {'alpha':0.7, 'clip_on':False}\n",
    "\n",
    "        ax.fill_between(ti, advrate_pos,  color = col.col('b'), **fillkws)\n",
    "        ax.fill_between(ti, advrate_neg,  color = col.col('r'), **fillkws)\n",
    "        ax.plot(d.time, advrate, '-', color = col.col('k'), lw = 1, clip_on = False)\n",
    "        \n",
    "        ax.invert_yaxis()\n",
    "        ax.set_ylabel('m day$^{-1}$', fontsize = fs)\n",
    "        \n",
    "        ax.set_title(glkey)\n",
    "        pretty.lrbars(ax)\n",
    "        ax.set_ylim(6, -14)\n",
    "\n",
    "        pretty.axthick(ax)\n",
    "        for yr in np.arange(2017, 2022):\n",
    "            vl_kws = {'alpha':0.3}\n",
    "            pl.vline(dt.date(yr, 10, 1), ax = ax, **vl_kws)\n",
    "            pl.vline(dt.date(yr, 4, 1), ax = ax, **vl_kws, ls = ':')\n",
    "            \n",
    "            if yr//2!=yr/2:\n",
    "                pl.fill_xrange(dt.date(yr, 1, 1), dt.date(yr, 12, 31), \n",
    "                           ax, color = col.col('g'), alpha = 0.2)\n",
    "\n",
    "        pretty.rotate_y(ax)\n",
    "        ax.set_xlim(dt.date(2016, 10, 1), dt.date(2022, 1, 1))\n",
    "        ax.set_yticks([-10, -5, 0, 5, ])\n",
    "        ax.tick_params(axis = 'x', width = 2.5, length = 5)\n",
    "        pretty.tickfs(fs, ax = ax)\n",
    "        ax.tick_params\n",
    "        fig.savefig(figdir_ew + glkey.replace(' ', '') + 'png', bbox_inches = 'tight', transparent = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "b30ec2f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Variable.__del__ at 0x7fb198085160>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 351, in __del__\n",
      "    if self._tk.getboolean(self._tk.call(\"info\", \"exists\", self._name)):\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n",
      "Exception ignored in: <function Image.__del__ at 0x7fb197b66a60>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/oyvindl/anaconda3/envs/oyv/lib/python3.8/tkinter/__init__.py\", line 4014, in __del__\n",
      "    self.tk.call('image', 'delete', self.name)\n",
      "RuntimeError: main thread is not in main loop\n"
     ]
    }
   ],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "11fa6c01",
   "metadata": {},
   "outputs": [],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "dc6e489d",
   "metadata": {},
   "outputs": [],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "4256db07",
   "metadata": {},
   "outputs": [],
   "source": [
    "pretty.tickfs?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f038de84",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Retreat rate\n",
    "advrate = adv.storis\n",
    "ti = np.arange(date2num(adv.time[0]), date2num(adv.time[-1])+1, 0.5)\n",
    "\n",
    "advrate_pos = ip.interp1(date2num(adv.time), advrate.copy(), ti)\n",
    "advrate_neg = ip.interp1(date2num(adv.time), advrate.copy(), ti)\n",
    "advrate_pos[advrate_pos<0] = np.nan\n",
    "advrate_neg[advrate_neg>0] = np.nan\n",
    "\n",
    "axs[2].plot(adv.time, advrate, '-', color = col.col('k'), lw = 1)\n",
    "axs[2].plot(adv.time, adv.hartog, ':', color = col.col('k'), lw = 1)\n",
    "\n",
    "fillkws = {'alpha':0.7}\n",
    "axs[2].fill_between(ti, advrate_pos,  color = col.col('b'), **fillkws)\n",
    "axs[2].fill_between(ti, advrate_neg,  color = col.col('r'), **fillkws)\n",
    "axs[2].invert_yaxis()\n",
    "axs[2].set_ylabel('m day$^{-1}$')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "04057b36",
   "metadata": {},
   "outputs": [],
   "source": [
    "ca()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a794557e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:oyv] *",
   "language": "python",
   "name": "conda-env-oyv-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
